CREATE TABLE `systwone`.`lmatches` ( `Hplayer` VARCHAR(1000) NOT NULL , `Aplayer` VARCHAR(1000) NOT NULL , `Hteam` VARCHAR(1000) NOT NULL , `Ateam` VARCHAR(1000) NOT NULL , `Hscore` INT NOT NULL , `Ascore` INT NOT NULL , `winner` VARCHAR(1000) NOT NULL , `looser` VARCHAR(1000) NOT NULL , `tomatch` VARCHAR(100) NOT NULL , `tarehe` VARCHAR(100) NOT NULL , `wakati` VARCHAR(100) NOT NULL , `debt` INT NOT NULL , `matchid` VARCHAR(1000) NOT NULL ) ENGINE = InnoDB;




CREATE TABLE `systwone`.`lmatches` ( `Hplayer` VARCHAR(1000) NOT NULL , `Aplayer` VARCHAR(1000) NOT NULL , `Hteam` VARCHAR(1000) NOT NULL , `Ateam` VARCHAR(1000) NOT NULL , `Hscore` INT NOT NULL , `Ascore` INT NOT NULL , `winner` VARCHAR(1000) NOT NULL , `looser` VARCHAR(1000) NOT NULL , `tomatch` VARCHAR(100) NOT NULL , `tarehe` VARCHAR(100) NOT NULL , `wakati` VARCHAR(100) NOT NULL , `debt` INT NOT NULL , `matchid` VARCHAR(1000) NOT NULL ) ENGINE = InnoDB;